actions:
  - type: 'tower'                                         # required
    name: 'slas2025'                             # required
    pipeline: 'https://github.com/nf-core/sarek'    # required
    workspace: 'SLAS2025/Demo'            # required
    compute-env: 'human-driven-bioinformatics'           # required
    # work-dir: 's3://your-bucket'                          # required
    revision: '3.5.0'                                      # required
    profile: 'test'                                       # optional
    params:                                               # optional
      outdir: "s3://$DESTINATION_BUCKET/$DESTINATION_PREFIX/"
    overwrite: False                                       # optional